### ISSUE TITLE
change size of badges and re-index them when dragged

### ISSUE THREAD

**Issue by javaJose** [WebDevBootcamp/AJAP#9]
this is the barebones code I was thinking of using... except hover (css or js)

$(element).onhover change the pixel size from x to x+25

$(element).draggable

when element is in new position...

```
$(element).sortByIndex
```

$(element).onrelease pixel size returns to x

**Comment by nw** [comment]
Nice pseudo code to break down the problem!

My question is why adjust the x on hover?

Why not use the css property 'resize'.

Then in jquery you can listen for the resize event

$(element).on('resize', function(event){
   // measure element for new size
});

Granted this does not work in IE.

**Comment by javaJose** [comment]
thanks I'll code it out at classtime

**Comment by javaJose** [comment]
It may be useful to drag and drop each school to reorder its display, so the most relevant one displays first, but... A better user experience might be:
Using D&D  to personalize our badges with tags such as "Like" or "Comment" so that we may "badge" our badges and share what we personalized.

**Comment by javaJose** [comment]
Or even more useful would be display the badge's title on hover since the shapes are abstract.
